name: Node.js CI with Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: QA
    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
        
    - name: Install Backend dependencies
      run: |
        cd backend
        npm install
        
    - name: Install Frontend dependencies
      run: |
        cd frontend
        npm install
        
    - name: Test with npm
      run: |
        cd backend
        npm test || true
        cd ../frontend
        npm test || true

  package:
    runs-on: ubuntu-latest
    environment: Staging
    needs: [test]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
        
    - name: Install Frontend dependencies
      run: |
        cd frontend
        npm install
        
    - name: Build Vue App
      run: |
        cd frontend
        npm run build
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: vue-build
        path: frontend/dist 
        
  docker-hub:
    runs-on: ubuntu-latest
    environment: Production
    needs: [package]
    steps:
    - uses: actions/checkout@v4
    
    - name: Create dist directory
      run: mkdir -p frontend/dist
      
    - name: Download Vue Build
      uses: actions/download-artifact@v4
      with:
        name: vue-build
        path: frontend/dist
        
    - name: Build & Push Docker image to Docker Hub
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: jesusvelazquezmx/powertech
        tags: latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
      runs-on: ubuntu-latest
      environment: Production
      needs: [docker-hub] # Solo se ejecuta si la imagen se subió con éxito
      steps:
        - name: Conectar a AWS y actualizar Docker
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.AWS_HOST }} # La IP del servidor EC2
            username: ubuntu # super usuario que viene con la imagen de AWS
            key: ${{ secrets.AWS_SSH_KEY }} # La llave .pem de AWS
            script: |
              # 1. Descarga la imagen más reciente
              docker pull jesusvelazquezmx/powertech:latest
              
              # 2. Borra el contenedor viejo
              docker rm -f powertech || true
              
              # 3. Levanta el nuevo inyectando las contraseñas
              docker run --name powertech -d -p 3000:3000 jesusvelazquezmx/powertech:latest
              
              # 4. Limpia la basura (imágenes viejas) para no llenar el disco duro
              docker image prune -f